#!/bin/bash
FUNCHECKCLASSPATH="/localhome/liftweb/funcheck/project/boot/scala-2.8.1/lib/scala-library.jar:/localhome/liftweb/funcheck/project/boot/scala-2.8.1/lib/scala-compiler.jar:/localhome/liftweb/funcheck/bin/purescala/purescala-definitions_2.8.1-1.0.jar:/localhome/liftweb/funcheck/bin/funcheck/funcheck-plugin_2.8.1-1.0.jar:/localhome/liftweb/funcheck/lib/z3.jar"

for f in "/localhome/liftweb/funcheck/bin/multisets-lib/multiset-placeholder-library_2.8.1-1.0.jar" "/localhome/liftweb/funcheck/bin/multisets/multiset-solver_2.8.1-1.0.jar" "/localhome/liftweb/funcheck/bin/orderedsets/ordered-sets-solver_2.8.1-1.0.jar" "/localhome/liftweb/funcheck/bin/setconstraints/type-inference-with-set-constraints_2.8.1-1.0.jar"; do
  if [ -e ${f} ]
  then
    FUNCHECKCLASSPATH=${FUNCHECKCLASSPATH}:${f}
  fi
done

SCALACCLASSPATH="/localhome/liftweb/funcheck/bin/multisets-lib/multiset-placeholder-library_2.8.1-1.0.jar:/localhome/liftweb/funcheck/bin/funcheck/funcheck-plugin_2.8.1-1.0.jar:/localhome/liftweb/funcheck/bin/purescala/purescala-definitions_2.8.1-1.0.jar"

LD_LIBRARY_PATH=/localhome/liftweb/libstdc++:/localhome/liftweb/z3/z3-2.19/lib \
scala -classpath ${FUNCHECKCLASSPATH}:${SCALACCLASSPATH} \
funcheck.Main -cp /localhome/liftweb/funcheck/bin/funcheck/funcheck-plugin_2.8.1-1.0.jar $@
