/* Copyright 2009-2016 EPFL, Lausanne */

package leon
package grammars

import purescala.Expressions._
import purescala.Types.TypeTree
import purescala.ExprOps.collect
import purescala.Extractors.IsTyped

/** Generates constants found in an [[leon.purescala.Expressions.Expr]].
  * Some constants that are generated by other grammars (like 0, 1) will be excluded
  */
case class Constants(e: Expr) extends SimpleExpressionGrammar {

  private val excluded: Set[Expr] = Set(
    InfiniteIntegerLiteral(1),
    InfiniteIntegerLiteral(0),
    IntLiteral(1),
    IntLiteral(0),
    BooleanLiteral(true),
    BooleanLiteral(false)
  )

  def generateSimpleProductions(implicit ctx: LeonContext) = {
    val literals = collect[Expr]{
      case l:Literal[_] => Set(l)
      case _ => Set()
    }(e)

    for (l <- (literals -- excluded).toSeq) yield {
      sTerminal(l.getType, l, Tags.Constant)
    }
  }
}
